baseURL: "https://your-website-address"
languageCode: "en-us"
title: "Hugo Template Renan Sigolo"

disableHugoGeneratorInject: true
enableRobotsTXT: true
publishdir: "dist"
minify: true
disableKinds:
  - taxonomy
  - term
  - RSS
